// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object H264RendererPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()
private open class H264RendererPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}

/**
 * Platform-channel bridge to the native H.264 hardware decoder.
 *
 * Lifecycle: call [initialize] once, [decodeFrame] for each incoming frame,
 * and [dispose] when the session ends.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface H264RendererApi {
  /**
   * Platform-channel bridge to the native H.264 hardware decoder.
   *
   * Lifecycle: call [initialize] once, [decodeFrame] for each incoming frame,
   * and [dispose] when the session ends.
   */
  fun initialize(width: Long, height: Long): Long
  /**
   * Pushes a raw H.264 Annex-B frame to the native decoder.
   *
   * Fire-and-forget: do not await this in the frame callback.
   */
  fun decodeFrame(frameData: ByteArray, isKeyframe: Boolean)
  /** Releases the native decoder and unregisters the Flutter texture. */
  fun dispose()

  companion object {
    /** The codec used by H264RendererApi. */
    val codec: MessageCodec<Any?> by lazy {
      H264RendererPigeonCodec()
    }
    /** Sets up an instance of `H264RendererApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: H264RendererApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bridge_view_client.H264RendererApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val widthArg = args[0] as Long
            val heightArg = args[1] as Long
            val wrapped: List<Any?> = try {
              listOf(api.initialize(widthArg, heightArg))
            } catch (exception: Throwable) {
              H264RendererPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bridge_view_client.H264RendererApi.decodeFrame$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val frameDataArg = args[0] as ByteArray
            val isKeyframeArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.decodeFrame(frameDataArg, isKeyframeArg)
              listOf(null)
            } catch (exception: Throwable) {
              H264RendererPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bridge_view_client.H264RendererApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.dispose()
              listOf(null)
            } catch (exception: Throwable) {
              H264RendererPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
