// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum H264RendererPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class H264RendererPigeonCodecReader: FlutterStandardReader {
}

private class H264RendererPigeonCodecWriter: FlutterStandardWriter {
}

private class H264RendererPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return H264RendererPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return H264RendererPigeonCodecWriter(data: data)
  }
}

class H264RendererPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = H264RendererPigeonCodec(readerWriter: H264RendererPigeonCodecReaderWriter())
}

/// Platform-channel bridge to the native H.264 hardware decoder.
///
/// Lifecycle: call [initialize] once, [decodeFrame] for each incoming frame,
/// and [dispose] when the session ends.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol H264RendererApi {
  /// Platform-channel bridge to the native H.264 hardware decoder.
  ///
  /// Lifecycle: call [initialize] once, [decodeFrame] for each incoming frame,
  /// and [dispose] when the session ends.
  func initialize(width: Int64, height: Int64) throws -> Int64
  /// Pushes a raw H.264 Annex-B frame to the native decoder.
  ///
  /// Fire-and-forget: do not await this in the frame callback.
  func decodeFrame(frameData: FlutterStandardTypedData, isKeyframe: Bool) throws
  /// Releases the native decoder and unregisters the Flutter texture.
  func dispose() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class H264RendererApiSetup {
  static var codec: FlutterStandardMessageCodec { H264RendererPigeonCodec.shared }
  /// Sets up an instance of `H264RendererApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: H264RendererApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Platform-channel bridge to the native H.264 hardware decoder.
    ///
    /// Lifecycle: call [initialize] once, [decodeFrame] for each incoming frame,
    /// and [dispose] when the session ends.
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bridge_view_client.H264RendererApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let widthArg = args[0] as! Int64
        let heightArg = args[1] as! Int64
        do {
          let result = try api.initialize(width: widthArg, height: heightArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Pushes a raw H.264 Annex-B frame to the native decoder.
    ///
    /// Fire-and-forget: do not await this in the frame callback.
    let decodeFrameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bridge_view_client.H264RendererApi.decodeFrame\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      decodeFrameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let frameDataArg = args[0] as! FlutterStandardTypedData
        let isKeyframeArg = args[1] as! Bool
        do {
          try api.decodeFrame(frameData: frameDataArg, isKeyframe: isKeyframeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      decodeFrameChannel.setMessageHandler(nil)
    }
    /// Releases the native decoder and unregisters the Flutter texture.
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bridge_view_client.H264RendererApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        do {
          try api.dispose()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
